internal struct Game: Codable, Identifiable {
    let id: Int
    let ageRatings: [Int]?
    let alternativeNames: [Int]?
    let category: Int?
    let cover: Int?
    let createdAt: Int?
    let externalGames: [Int]?
    let firstReleaseDate: Int?
    let gameModes: [Int]?
    let genres: [Int]?
    let involvedCompanies: [Int]?
    let keywords: [Int]?
    let name: String
    let platforms: [Int]?
    let playerPerspectives: [Int]?
    let releaseDates: [Int]?
    let screenshots: [Int]?
    let similarGames: [Int]?
    let slug: String
    let storyline: String?
    let summary: String?
    let tags: [Int]?
    let themes: [Int]?
    let updatedAt: Int?
    let url: String
    let videos: [Int]?
    let websites: [Int]?
    let checksum: String
    let gameLocalizations: [Int]?
    let aggregatedRating: Double?
    let aggregatedRatingCount: Int?
    let totalRating: Double?
    let totalRatingCount: Int?
}
